spring:
  application:
    name=entra-id
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/d1de9ec6-0a1d-4780-90a7-c90800d2e75b/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: c9f01ebc-f7ac-4cba-8cfe-c1087a87d1e2
            client-secret: ciW8Q~jsXmbX-LX.NWvQATFN8gtp2FeQgwGZ.cR1
            scope:
              - openid
              - email
              - profile
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
# Group mapping

baeldung:
  jwt:
    authorization:
      group-to-authorities:
        "ceef656a-fca9-49b6-821b-f7543b7065cb": BAELDUNG_RW
        "eaaecb69-ccbc-4143-b111-7dd1ce1d99f1": BAELDUNG_RO,BAELDUNG_ADMIN